package com.dumuzeyn.mp3player

/** Theme-only launcher targets required for Android 12+ splash resources. */
object LauncherThemeActivities {
    class CustomBlueLight : MainActivity()
    class CustomBlueDark : MainActivity()
    class CustomRedLight : MainActivity()
    class CustomRedDark : MainActivity()
    class CustomGreenLight : MainActivity()
    class CustomGreenDark : MainActivity()
    class CustomPinkLight : MainActivity()
    class CustomPinkDark : MainActivity()
    class CustomOrangeLight : MainActivity()
    class CustomOrangeDark : MainActivity()

    // GENERATED CUSTOM FOREGROUND ACTIVITIES START
    class CustomBlueLightForegroundRed : MainActivity()
    class CustomBlueLightForegroundGreen : MainActivity()
    class CustomBlueLightForegroundPink : MainActivity()
    class CustomBlueLightForegroundOrange : MainActivity()
    class CustomBlueDarkForegroundRed : MainActivity()
    class CustomBlueDarkForegroundGreen : MainActivity()
    class CustomBlueDarkForegroundPink : MainActivity()
    class CustomBlueDarkForegroundOrange : MainActivity()
    class CustomRedLightForegroundBlue : MainActivity()
    class CustomRedLightForegroundGreen : MainActivity()
    class CustomRedLightForegroundPink : MainActivity()
    class CustomRedLightForegroundOrange : MainActivity()
    class CustomRedDarkForegroundBlue : MainActivity()
    class CustomRedDarkForegroundGreen : MainActivity()
    class CustomRedDarkForegroundPink : MainActivity()
    class CustomRedDarkForegroundOrange : MainActivity()
    class CustomGreenLightForegroundBlue : MainActivity()
    class CustomGreenLightForegroundRed : MainActivity()
    class CustomGreenLightForegroundPink : MainActivity()
    class CustomGreenLightForegroundOrange : MainActivity()
    class CustomGreenDarkForegroundBlue : MainActivity()
    class CustomGreenDarkForegroundRed : MainActivity()
    class CustomGreenDarkForegroundPink : MainActivity()
    class CustomGreenDarkForegroundOrange : MainActivity()
    class CustomPinkLightForegroundBlue : MainActivity()
    class CustomPinkLightForegroundRed : MainActivity()
    class CustomPinkLightForegroundGreen : MainActivity()
    class CustomPinkLightForegroundOrange : MainActivity()
    class CustomPinkDarkForegroundBlue : MainActivity()
    class CustomPinkDarkForegroundRed : MainActivity()
    class CustomPinkDarkForegroundGreen : MainActivity()
    class CustomPinkDarkForegroundOrange : MainActivity()
    class CustomOrangeLightForegroundBlue : MainActivity()
    class CustomOrangeLightForegroundRed : MainActivity()
    class CustomOrangeLightForegroundGreen : MainActivity()
    class CustomOrangeLightForegroundPink : MainActivity()
    class CustomOrangeDarkForegroundBlue : MainActivity()
    class CustomOrangeDarkForegroundRed : MainActivity()
    class CustomOrangeDarkForegroundGreen : MainActivity()
    class CustomOrangeDarkForegroundPink : MainActivity()
    // GENERATED CUSTOM FOREGROUND ACTIVITIES END
}
